spring:
  profiles:
    include:
      account

logging:
  level:
    love:
      forte:
        simbot: debug

# 上传图片失败时的重试次数
image-upload-retry: 3
# 图片处理时的缓存文件夹
image-cache: /root/bin/imageCache

# pixiv cookie。将会自动更新。
cookie-file: pixiv_cookie.ini
# 反屏蔽时分隔图片的份数
split-number: 3
# 是否发送原图
source-image: true
# 群冷却。单位：秒
group-delay: 20

# 代理信息
http-proxy:
  host: 127.0.0.1
  port: 1080
  protocol: http
  enable: false